name: Hello, World # ワークフロー名 on: push # イベント
jobs: # ジョブ
  my_first_job: # ジョブのID
  name: Greeting # ジョブ名
  runs-on: ubuntu-latest # 実行される仮想環境 
  steps: # ジョブ内で実行される処理
  - run: echo "hello, world"
on:
  push:
    branches:
      [my_branch]